#!/bin/sh
# Run prettier on all staged files
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0

# If git is reporting that your prettified files are still modified after committing, you may need to add a post-commit script to update git’s index.
# #!/bin/sh
# git update-index -g